# Generated by Django 2.0.3 on 2018-03-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180314_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='12345', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='12345', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='password',
            field=models.CharField(default='12345', max_length=50),
        ),
    ]
