# Generated by Django 2.0.3 on 2018-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180314_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=50),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='username',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=50),
        ),
    ]
